### ISSUE TITLE
TimeOut

### ISSUE THREAD

**Issue by besanilla1** [DamnedFacts/actuonix-lac#1]
Thanks to publish this code, very useful, I would like your help I have getting an timeout error
Traceback (most recent call last):
  File "C:\sqaLynott\lynott_fw_test\sample_scripts\ActuatorPoC\square_wave.py", line 73, in <module>
    feedback = button.get_feedback()
  File "C:\sqaLynott\lynott_fw_test\sample_scripts\ActuatorPoC\liblac\lac.py", line 147, in get_feedback
    return self.send_data(self._GET_FEEDBACK)
  File "C:\sqaLynott\lynott_fw_test\sample_scripts\ActuatorPoC\liblac\lac.py", line 49, in send_data
    response = self.device.read(0x81, 3, 100)  # 3 because there's three bytes to a packet
  File "C:\Python27\lib\site-packages\usb\core.py", line 988, in read
    self.__get_timeout(timeout))
  File "C:\Python27\lib\site-packages\usb\backend\libusb1.py", line 833, in bulk_read
    timeout)
  File "C:\Python27\lib\site-packages\usb\backend\libusb1.py", line 936, in __read
    _check(retval)
  File "C:\Python27\lib\site-packages\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 10060] Operation timed out

**Comment by DamnedFacts** [comment]
Make sure you don't have multiple processes, or threads communicating to the same device without some sort of serialized coordination of commands. For example, I can get this error if I call `l.get_feedback()`, if `l` is an instance of the `LAC` class, with two or more threads accessing the object `l`. What happens is that you are issuing multiple calls to `l.get_feedback()`, some of which are overlapping, and conflicting with an already in-progress call `l.get_feedback()` in another thread.

Try mutex, semaphore, or global Queue object queuing requests.
